volumes:
  postgres-data:
  keycloak-db-data:

networks:
  euleops-net:

services:

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: LeiserHazard1996!
      POSTGRES_DB: euleops
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - euleops-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.2
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - euleops-net

  kafka:
    image: confluentinc/cp-kafka:7.5.2
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - euleops-net

  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - euleops-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    restart: unless-stopped
    depends_on:
      - keycloak-db
    command:
      [
        "start-dev",
        "--import-realm"
      ]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak/realm-export:/opt/keycloak/data/import:ro
    ports:
      - "8080:8080"
    networks:
      - euleops-net

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    depends_on:
      - postgres
      - kafka
      - keycloak
    ports:
      - "8081:8080"
    networks:
      - euleops-net
    environment:
      SPRING_PROFILES_ACTIVE: docker

  auth-svc:
    build:
      context: .
      dockerfile: services/auth-svc/Dockerfile
    depends_on:
      - postgres
      - kafka
      - keycloak
    ports:
      - "8182:8080"
    networks:
      - euleops-net
    environment:
      SPRING_PROFILES_ACTIVE: docker

  notification-svc:
    build:
      context: .
      dockerfile: services/notification-svc/Dockerfile
    depends_on:
      - postgres
      - kafka
    ports:
      - "8183:8080"
    networks:
      - euleops-net
    environment:
      SPRING_PROFILES_ACTIVE: docker
