version: "3.8"

volumes:
  postgres-data:
  keycloak-db-data:

networks:
  euleops-net:

services:

  # PostgreSQL para Outbox, Auth y Cache
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: euleops
      POSTGRES_DB: euleops
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - euleops-net

  # Kafka + ZooKeeper para eventos internos
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.2
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - euleops-net

  kafka:
    image: confluentinc/cp-kafka:7.5.2
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"   # externo
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    networks:
      - euleops-net

  # Keycloak para login y roles
  keycloak-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - euleops-net

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    restart: unless-stopped
    depends_on:
      - keycloak-db
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    networks:
      - euleops-net
