replicaCount: 2             # se escalará con HPA

image:
  repository: "{{ .Values.global.imageRegistry }}/risk-engine"
  tag: "1.0.0"
  pullPolicy: IfNotPresent

env:
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.global.kafka.bootstrapServers }}"
  SCHEMA_REGISTRY_URL:     "{{ .Values.global.schemaRegistry.url }}"
  MODEL_URI:               "s3://models/risk/gnn-v1.mar"
  FEATURE_STORE_HOST:      "feast-online"
  GPU_ENABLED:             "true"       # se sustituye a "false" en dev
  LOG_LEVEL:               "INFO"

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi
    nvidia.com/gpu: 1       # quitar o ajustar si no usas GPU

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60     # TorchServe es CPU-bound si no hay GPU

service:
  port: 8080        # REST + /metrics
