spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:db}:5432/notification
    username: ${DB_USER}
    password: ${DB_PASS}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
logging:
  level:
    root: INFO
notification:
  host: http://localhost:8183
