spring:
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASS}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from: ${MAIL_FROM:lalbertomurillo1996@gmail.com}

jwt:
  secret: ${JWT_SECRET}
