spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/euleops
    username: postgres
    password: LeiserHazard1996!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9093

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: euleops4!
