replicaCount: 2

image:
  repository: "{{ .Values.global.imageRegistry }}/alert-service"
  tag: "0.7.0"
  pullPolicy: IfNotPresent

env:
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.global.kafka.bootstrapServers }}"
  SCHEMA_REGISTRY_URL:     "{{ .Values.global.schemaRegistry.url }}"
  ALERT_TOPIC_PREFIX:      "alert."
  RULES_BUCKET:            "s3://rules/"          # donde se guardan JSONLogic
  SLACK_WEBHOOK_URL:       "https://hooks.slack.com/services/TOKEN"
  SMS_PROVIDER_URL:        "https://sms.gateway/api"
  LOG_LEVEL:               "INFO"

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

service:
  port: 8080              # REST /rules, /health
