replicaCount: 2

image:
  repository: "{{ .Values.global.imageRegistry }}/ingest"   # heredado del umbrella
  tag: "0.2.3"
  pullPolicy: IfNotPresent

env:
  KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.global.kafka.bootstrapServers }}"
  SCHEMA_REGISTRY_URL: "{{ .Values.global.schemaRegistry.url }}"
  TRANSACTIONAL_ID_PREFIX: ingest         # cada Pod añade su ordinal
  APP_LOG_LEVEL: "INFO"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

service:
  port: 8080         # health-check y métricas
