apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "inventory.fullname" . }}-env
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
  DB_URL:                    {{ .Values.env.DB_URL | quote }}
  OUTBOX_TOPIC:              {{ .Values.env.OUTBOX_TOPIC | quote }}
  LOG_LEVEL:                 {{ .Values.env.LOG_LEVEL | quote }}
