apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingest.fullname" . }}-env
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
  SCHEMA_REGISTRY_URL:    {{ .Values.env.SCHEMA_REGISTRY_URL | quote }}
  TRANSACTIONAL_ID_PREFIX: {{ .Values.env.TRANSACTIONAL_ID_PREFIX | quote }}
  APP_LOG_LEVEL:          {{ .Values.env.APP_LOG_LEVEL | quote }}
